import type { MetadataRoute } from 'next'

/**
 * Web app manifest — installable PWA / store-shell entry.
 * Icons generated by: npm run icons:generate
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: '/',
    name: 'Beacon · School Suite',
    short_name: 'Beacon',
    description:
      'The full school suite for any school — academics, family communications, payments, and principal operations.',
    start_url: '/login',
    scope: '/',
    display: 'standalone',
    orientation: 'any',
    background_color: '#0a1628',
    theme_color: '#0a1628',
    categories: ['education', 'productivity', 'business'],
    lang: 'en',
    dir: 'ltr',
    icons: [
      {
        src: '/icons/icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/icon-512-maskable.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/icons/apple-touch-icon.png',
        sizes: '180x180',
        type: 'image/png',
        purpose: 'any',
      },
    ],
    shortcuts: [
      {
        name: 'Family Desk',
        short_name: 'Desk',
        description: 'Write notes home and read family replies',
        url: '/desk',
        icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }],
      },
      {
        name: 'Teacher Quick',
        short_name: 'Quick',
        description: 'Phone-first attendance, scores, and pulse',
        url: '/teacher/quick',
        icons: [{ src: '/icons/icon-192.png', sizes: '192x192' }],
      },
    ],
  }
}
